### ISSUE TITLE
Integrar o formulário com a API

### ISSUE THREAD

**Issue by pedro-vasconcelos** [laravel-portugal/frontend-2020#2]
## Colocar um `community link` no repositório de informação do Laravel Portugal

- [ ] Implementar o comportamento do formulário no front-end (ver requisitos)

### Requisitos do formulário para submissão de um `community link`

Os campos do formulário são:

- Website
- Image
- Titulo
- Nome
- E-mail
- Descrição
- Tags

#### O campo `Website` 
O campo Website é usado como link de destino do `card` que representa o `community link` colocado pelo utilizador. Este endereço contém a informação principal que o utilizador quer partilhar com a comunidade.

- Critério de validação: 
  - obrigatório
  - o conteúdo deve ser um endereço URL válido (usar a regra de validação da framework)
  - o endereço deve responder com um http status 200 (usar uma custom rule na framework)
  - o endereço deve ser único na BD (usar uma custom rule na framework)

- Trigger da validação
  - A validação é feita no evento blur da input-box

- Durante o processo de validação do campo
  - Colocar a input-box em read-only
  - ***Testar isto:*** Desligar o readonly e testar fazer alterações ao conteúdo para ver qual é o comportamento do Livewire (ex: com a ligação throtteled em 3G, alterar o URL a meio do primeiro pedido de AJAX, provocando um segundo pedido. Verificar se o primeiro foi cancelado e o que acontece no render)

- Se passar na validação:
  - Colocar um check a verde para sinalizar ao utilizador que o URL é válida
  - Trigger do evento `fetch preview` no component `image`.

- Definir as mensagens de erro para cada critério de validação

- Testes:
  - Testes Pest aos critérios de validação com a facade do Livewire
  - Testes Dusk para testar as regras e as mensagens de erro

#### O campo `Image` 

Este campo pretende ser um complemento visual, fazendo uma previsão sobre o conteúdo em causa. O sistema tentar gerar uma imagem com base na informação disponível no URL indicado pelo utilizador e dá a opção ao utilizador de enviar uma imagem para o sistema. O funcionamento será o seguinte:

Após receber o event `fetch preview` informamos o utilizador que estamos a gerar uma imagem para o `community link`, dando a opção de cancelar com o descritivo `cancelar e submeter a minha imagem`. Se o utilizador cancelar, mostramos uma drop-zone para o utilizador enviar a imagem.

No final apresentamos a imagem gerada, onde o utilizador volta a ter a opção de manter a imagem (não fazer nada) ou colocar a sua, através de uma opção `submeter a minha imagem`.

```
O processo de tentativa de gerar a imagem é a seguinte:
2.1 Tentar apanhar a Meta Info que tenha Social Media Preview
2.1.1 Tentar as várias meta tags possíveis (Spatie/crawler)
2.1.2 Em alternativa, gerar uma imagem com a Spatie BrowserShot
```

### Tasks / Actions
- [ ] Criar as regras para o campo Website
- [ ] Criar a Custom Rule para verificar o response code
- [ ] Criar a Custom Rule para verificar se o URL ainda não existe no sistema (@josepostiga necessitamos deste end-point)
- [ ] Configurar os eventos e os triggers para o campo Website
- [ ] Implementar as mensagens a aparecer durante o processo de validação e no final
- [ ] Implementar a Drop-Zone para o campo Image
- [ ] Implementar as mensagens de status e de acção para o utilizador
- [ ] Criar as mensagens de sucesso e de erro
- [ ] Criar os `Feature Tests` para os critérios de validação do formulário
- [ ] Criar os testes `End-to-End` para o formulário

Temos de enviar os seguintes campos:

            'link' => ['required', 'string'],
            'title' => ['required', 'string'],
            'author_name' => ['required', 'string'],
            'author_email' => ['required', 'email'],
            'description' => ['required', 'string'],

Temos de receber as tags para colocar no formulário:

            'tags' => ['required', 'array'],

Este campo, se for usado pelo utilizador cancela o Job que está a tentar criar uma Image Preview para o link com base no URL que o utilizador deu:

            'cover_image' => ['required', 'image'],
            'cover_image' => $request->file('cover_image')->store('cover_images'),
